const cakes = [
	{
        id: 1,
        name: "Chocolate Dream",
        basePrice: 35.99,
        image: "/images/20240513_182430.webp",
        description: "Rich chocolate cake with creamy chocolate frosting.",
        fillings: [
            { name: "Chocolate Ganache", price: 0 },
            { name: "Raspberry", price: 2 },
            { name: "Dulce de Leche", price: 3 },
            { name: "Vanilla Cream", price: 1 },
        ],
        bases: [
            { name: "Chocolate", price: 0 },
            { name: "Vanilla", price: 0 },
            { name: "Marble", price: 2 },
        ],
    },
	{
		id: 2,
		name: "Strawberry Delight",
		basePrice: 32.99,
		image: "/images/20240516_091853.webp",
		description:
			"Light vanilla cake with fresh strawberries and strawberry frosting.",
		fillings: [
			{ name: "Strawberry Cream", price: 0 },
			{ name: "Lemon Curd", price: 2 },
			{ name: "Vanilla Cream", price: 1 },
			{ name: "Chocolate", price: 2 },
		],
		bases: [
			{ name: "Vanilla", price: 0 },
			{ name: "Strawberry", price: 2 },
			{ name: "Lemon", price: 2 },
		],
	},
	{
		id: 3,
		name: "Vanilla Bliss",
		basePrice: 30.99,
		image: "/images/20240523_153232.webp",
		description:
			"Classic vanilla cake with smooth vanilla buttercream frosting.",
		fillings: [
			{ name: "Vanilla Buttercream", price: 0 },
			{ name: "Chocolate", price: 2 },
			{ name: "Dulce de Leche", price: 3 },
			{ name: "Lemon", price: 2 },
		],
		bases: [
			{ name: "Vanilla", price: 0 },
			{ name: "Almond", price: 2 },
			{ name: "Lemon", price: 2 },
		],
	},
	{
		id: 4,
		name: "Red Velvet Romance",
		basePrice: 37.99,
		image: "/images/1000307419.webp",
		description: "Velvety red cake with cream cheese frosting.",
		fillings: [
			{ name: "Cream Cheese", price: 0 },
			{ name: "Chocolate", price: 2 },
			{ name: "Raspberry", price: 2 },
			{ name: "Vanilla Cream", price: 1 },
		],
		bases: [
			{ name: "Red Velvet", price: 0 },
			{ name: "Chocolate", price: 0 },
			{ name: "Vanilla", price: 0 },
		],
	},
	{
		id: 5,
		name: "Lemon Zest Delight",
		basePrice: 33.99,
		image: "/images/1000904494.webp",
		description: "Tangy lemon cake with lemon zest frosting.",
		fillings: [
			{ name: "Lemon Curd", price: 0 },
			{ name: "Raspberry", price: 2 },
			{ name: "Vanilla Cream", price: 1 },
			{ name: "Blueberry", price: 2 },
		],
		bases: [
			{ name: "Lemon", price: 0 },
			{ name: "Vanilla", price: 0 },
			{ name: "Almond", price: 2 },
		],
	},
	{
		id: 6,
		name: "Caramel Cream Dream",
		basePrice: 36.99,
		image: "/images/IMG_0972.webp",
		description: "Moist caramel cake with caramel cream frosting.",
		fillings: [
			{ name: "Caramel Cream", price: 0 },
			{ name: "Chocolate", price: 2 },
			{ name: "Dulce de Leche", price: 3 },
			{ name: "Vanilla Cream", price: 1 },
		],
		bases: [
			{ name: "Caramel", price: 0 },
			{ name: "Vanilla", price: 0 },
			{ name: "Chocolate", price: 0 },
		],
	},

	{
		id: 6,
		name: "Caramel Cream Dream",
		basePrice: 36.99,
		image: "/images/IMG_0972.webp",
		description: "Moist caramel cake with caramel cream frosting.",
		fillings: [
			{ name: "Caramel Cream", price: 0 },
			{ name: "Chocolate", price: 2 },
			{ name: "Dulce de Leche", price: 3 },
			{ name: "Vanilla Cream", price: 1 },
		],
		bases: [
			{ name: "Caramel", price: 0 },
			{ name: "Vanilla", price: 0 },
			{ name: "Chocolate", price: 0 },
		],
	},
	{
		id: 7,
		name: "Caramel Cream Dream",
		basePrice: 36.99,
		image: "/images/IMG_1213.webp",
		description: "Moist caramel cake with caramel cream frosting.",
		fillings: [
			{ name: "Caramel Cream", price: 0 },
			{ name: "Chocolate", price: 2 },
			{ name: "Dulce de Leche", price: 3 },
			{ name: "Vanilla Cream", price: 1 },
		],
		bases: [
			{ name: "Caramel", price: 0 },
			{ name: "Vanilla", price: 0 },
			{ name: "Chocolate", price: 0 },
		],
	},
	{
		id: 8,
		name: "Caramel Cream Dream",
		basePrice: 36.99,
		image: "/images/IMG_1218_jpg-2.webp",
		description: "Moist caramel cake with caramel cream frosting.",
		fillings: [
			{ name: "Caramel Cream", price: 0 },
			{ name: "Chocolate", price: 2 },
			{ name: "Dulce de Leche", price: 3 },
			{ name: "Vanilla Cream", price: 1 },
		],
		bases: [
			{ name: "Caramel", price: 0 },
			{ name: "Vanilla", price: 0 },
			{ name: "Chocolate", price: 0 },
		],
	},
	{
		id: 9,
		name: "Caramel Cream Dream",
		basePrice: 36.99,
		image: "/images/IMG_1293.webp",
		description: "Moist caramel cake with caramel cream frosting.",
		fillings: [
			{ name: "Caramel Cream", price: 0 },
			{ name: "Chocolate", price: 2 },
			{ name: "Dulce de Leche", price: 3 },
			{ name: "Vanilla Cream", price: 1 },
		],
		bases: [
			{ name: "Caramel", price: 0 },
			{ name: "Vanilla", price: 0 },
			{ name: "Chocolate", price: 0 },
		],
	},
];