export const cakes = [
	{
		id: 1,
		name: "Mini cake",
		basePrice: 13.0,
		image: "/images/IMG_1293.webp",
		description: "4 porciones",
		rellenos: [
			{ name: "Chocolate", price: 1.5 },
			{ name: "Choco Oreo", price: 2 },
			{ name: "Choco Pirulin", price: 3 },
			{ name: "arequipe", price: 0.75 },
		],
		SaborDelPonque: [
			{ name: "Vainilla", price: 0 },
			{ name: "Marmoliado", price: 0 },
			{ name: "chocolate", price: 0 },
		],
	},
	{
		id: 2,
		name: "Tortica Pequeña",
		basePrice: 25.0,
		image: "/images/20240516_091853.webp",
		description: "8 Porciones",
		rellenos: [
			{ name: "Chocolate", price: 4 },
			{ name: "Choco Oreo", price: 5 },
			{ name: "Choco Pirulin", price: 6 },
			{ name: "arequipe", price: 1.5 },
		],
		SaborDelPonque: [
			{ name: "Vainilla", price: 0 },
			{ name: "Marmoliado", price: 0 },
			{ name: "chocolate", price: 0 },
		],
	},
	{
		id: 3,
		name: "Tortica Mediana",
		basePrice: 38.0,
		image: "/images/20240523_153232.webp",
		description: "12 a 15 porciones",
		rellenos: [
			{ name: "Chocolate", price: 7 },
			{ name: "Choco Oreo", price: 8 },
			{ name: "Choco Pirulin", price: 11 },
			{ name: "arequipe", price: 2.5 },
		],
		SaborDelPonque: [
			{ name: "Vainilla", price: 0 },
			{ name: "Marmoliado", price: 0 },
			{ name: "chocolate", price: 0 },
		],
	},
	{
		id: 4,
		name: "Tortita Grande",
		basePrice: 50,
		image: "/images/1000307419.webp",
		description: "20 Porciones",
		rellenos: [
			{ name: "Chocolate", price: 9 },
			{ name: "Choco Oreo", price: 13 },
			{ name: "Choco Pirulin", price: 17 },
			{ name: "arequipe", price: 3 },
		],
		SaborDelPonque: [
			{ name: "Vainilla", price: 0 },
			{ name: "Marmoliado", price: 0 },
			{ name: "chocolate", price: 0 },
		],
	},
	{
		id: 5,
		name: "Mini cake de corazon",
		basePrice: 13.0,
		image: "/images/IMG_1293.webp",
		description: "4 porciones",
		rellenos: [
			{ name: "Chocolate", price: 1.5 },
			{ name: "Choco Oreo", price: 2 },
			{ name: "Choco Pirulin", price: 3 },
			{ name: "arequipe", price: 0.75 },
		],
		SaborDelPonque: [
			{ name: "Vainilla", price: 0 },
			{ name: "Marmoliado", price: 0 },
			{ name: "chocolate", price: 0 },
		],
	},
	{
		id: 7,
		name: "Tortica Pequeña de corazon",
		basePrice: 25.0,
		image: "/images/20240516_091853.webp",
		description: "8 Porciones",
		rellenos: [
			{ name: "Chocolate", price: 4 },
			{ name: "Choco Oreo", price: 5 },
			{ name: "Choco Pirulin", price: 6 },
			{ name: "arequipe", price: 1.5 },
		],
		SaborDelPonque: [
			{ name: "Vainilla", price: 0 },
			{ name: "Marmoliado", price: 0 },
			{ name: "chocolate", price: 0 },
		],
	},
	{
		id: 8,
		name: "Tortica Mediana de corazon",
		basePrice: 38.0,
		image: "/images/20240523_153232.webp",
		description: "12 a 15 porciones",
		rellenos: [
			{ name: "Chocolate", price: 7 },
			{ name: "Choco Oreo", price: 8 },
			{ name: "Choco Pirulin", price: 11 },
			{ name: "arequipe", price: 2.5 },
		],
		SaborDelPonque: [
			{ name: "Vainilla", price: 0 },
			{ name: "Marmoliado", price: 0 },
			{ name: "chocolate", price: 0 },
		],
	},
	{
		id: 9,
		name: "Tortita Grande de corazon",
		basePrice: 50,
		image: "/images/1000307419.webp",
		description: "20 Porciones",
		rellenos: [
			{ name: "Chocolate", price: 9 },
			{ name: "Choco Oreo", price: 13 },
			{ name: "Choco Pirulin", price: 17 },
			{ name: "arequipe", price: 3 },
		],
		SaborDelPonque: [
			{ name: "Vainilla", price: 0 },
			{ name: "Marmoliado", price: 0 },
			{ name: "chocolate", price: 0 },
		],
	},
];